### ISSUE TITLE
Cannot access the web site

### ISSUE THREAD

**Issue by Ja-Jager** [wokwi/esp32-idf-hello-wifi#4]
I am having a problem where I can get some information about wifi, ssid, etc. from the code of this project. Another effect I'm trying to achieve now is to access something like http://api.ipify.io to get the public address. I tried some of the ESP-IDF code to access the public address, and found that I can successfully connect to the internet on the physical ESP32S3 to get the public address. However, I can only achieve networking with wokwi simulation, not getting the public address. My guess is that the wokwi emulation does not enable access to the web address.
Is there any way to solve this problem? Thanks!🙇

**Comment by urish** [comment]
Hi, have you read the docs about the WiFi access? 

https://docs.wokwi.com/guides/esp32-wifi

**Comment by Ja-Jager** [comment]
So I can only use private gateway to access the webpage?

**Comment by urish** [comment]
If the page is publicly accessible, the public gateway should work too
