### ISSUE TITLE
Is it no longer possible to use c++ (main.cpp) with Esp IDF?

### ISSUE THREAD

**Issue by OsvaldoTCF** [wokwi/esp32-idf-hello-wifi#7]
**Code:**
https://wokwi.com/projects/410135743409582081

cc1: fatal error: /home/wokwi/esp-project-esp32c3/main/src/main.c: No such file or directory
compilation terminated.

**Comment by urish** [comment]
You can use esp-idf with C++, but you'll have to compile the code on your machine (not inside Wokwi)
